import type { Project, User, SurveyType } from '../../types';
import type { QueryParams, PaginatedResponse } from '../api/client';
import { ApiClient } from '../api/client';

// Use Vite environment variables
const getSupabaseUrl = () => import.meta.env.VITE_SUPABASE_URL || '';
const getSupabaseKey = () => import.meta.env.VITE_SUPABASE_ANON_KEY || '';

export class SupabaseService extends ApiClient {
  private supabaseUrl: string;
  private supabaseKey: string;

  constructor() {
    const baseURL = `${getSupabaseUrl()}/functions/v1`;
    super(baseURL, {
      'x-application': 'aa2000-app',
      'x-version': '1.0.0',
    });

    this.supabaseUrl = getSupabaseUrl();
    this.supabaseKey = getSupabaseKey();
  }

  // Generated by Supabase edge functions (not shown for brevity)
  async getProjects(params?: QueryParams) {
    return this.get<any>('/projects', params);
  }

  async getProject(id: string) {
    return this.get<any>(`/projects/${id}`);
  }

  async createProject(data: any) {
    return this.post<any>('/projects', data);
  }

  async updateProject(id: string, data: any) {
    return this.put<any>(`/projects/${id}`, data);
  }

  async deleteProject(id: string) {
    return this.delete<any>(`/projects/${id}`);
 }

  async getUsers(params?: QueryParams) {
    return this.get<any>('/users', params);
  }

  async createUser(data: any) {
    return this.post<any>('/users', data);
  }

  async getSurveys(projectId?: string, type?: SurveyType) {
    const params: QueryParams = {};
    if (projectId) params.filter = { ...params.filter, projectId };
    if (type) params.filter = { ...params.filter, type };
    return this.get<any>('/surveys', params);
  }

  async getSurvey(id: string) {
    return this.get<any>(`/surveys/${id}`);
  }

  async createSurvey(data: any) {
    return this.post<any>('/surveys', data);
  }

  async updateSurvey(id: string, data: any) {
    return this.put<any>(`/surveys/${id}`, data);
  }

  async deleteSurvey(id: string) {
    return this.delete<any>(`/surveys/${id}`);
  }

  async uploadFile(file: File, path: string) {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('path', path);

    const response = await fetch(`${this.supabaseUrl}/storage/v1/object/${path}`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${this.supabaseKey}`,
      },
      body: formData,
    });

    if (!response.ok) {
      throw new Error('File upload failed');
    }

    const data = await response.json();
    return { success: true, data };
  }
}
